name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 0.1.9
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  http: ^0.12.2
  crypto: ^2.1.5
  convert: ^2.1.1
  xml: ^4.5.1
  buffer: ^1.0.7
  intl: ^0.16.1
  mime: ^0.9.7
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  html: ^0.14.0+4
