name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.5.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.1
  crypto: ^3.0.0
  convert: ^3.0.0
  xml: ^6.1.0
  buffer: ^1.1.0
  intl: ^0.17.0
  mime: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.0
